<!doctype html>
<!-- Try setting a maximum size to the page? -->
<html>
<head>

<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!-- POSSIBLY REMOVE OR MODIFY TAG? TEST ON 1080p DISPLAY <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
<meta charset="utf-8">
<title>Automotive - Mechanical Engineering</title>

<!-- Icon for webpage -->
<link rel="shortcut icon" href="Img/favicon.ico">
	
<!-- Link to CSS -->
<link href="CSS/main.css" rel="stylesheet" type="text/css">
	
<!-- Link to custom icons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
	
<!-- Link to slideshow script -->
<script type="text/javascript" src="js/slideshow.js"></script>

</head>

<body>
	
<header>


	
</header>

<!-- Navigation bar at the top of the page. -->	
<?php 
	$active = "branches";
	require 'navbar.php';
?>

<br>
<br>
<br>
<br>
<br>
<br>
<br>	
	
<!-- Start Main Body -->
<div class="bodyboxtitletext">
	<p>Automotive Engineering</p>
</div>
	
<hr style="margin-right: 10%; margin-left: 5%;">

<div class="bodyboxsubtitletext">	
	<p>This page contains all the information you need relating to automotive engineering.</p>
</div>

<div class="bodyboxmaintext">
	<p>Automotive engineering focuses on the design of vehicles and the like.</p>
</div>	

<br>
<br>
<br>
<br>
<br>

<div class="bodyboxbravetitle">
	<p>About Automotive Engineering</p>
<hr>
</div>	

<div class="bodyboxbravetext">
	<p>Automotive engineering, along with aerospace engineering and naval architecture, is a branch of vehicle engineering, incorporating elements of mechanical, electrical, electronic, software, and safety engineering as applied to the design, manufacture and operation of motorcycles, automobiles, and trucks and their respective engineering subsystems. It also includes modification of vehicles. Manufacturing domain deals with the creation and assembling the whole parts of automobiles is also included in it. The automotive engineering field is research -intensive and involves direct application of mathematical models and formulas. The study of automotive engineering is to design, develop, fabricate, and test vehicles or vehicle components from the concept stage to production stage. Production, development, and manufacturing are the three major functions in this field.</p>
	
	<p>Automotive Engineering is a branch study of engineering which teaches manufacturing, designing, mechanical mechanisms as well operations of automobiles. It is an introduction to vehicle engineering which deals with motorcycles, cars, buses, trucks, etc. It includes branch study of mechanical, electronic, software and safety elements. Some of the engineering attributes and disciplines that are of importance to the automotive engineer and many of the other aspects are included in it:</p>
	
	<p><b>Safety engineering:</b> Safety engineering is the assessment of various crash scenarios and their impact on the vehicle occupants. These are tested against very stringent governmental regulations. Some of these requirements include: seat belt and air bag functionality testing, front and side impact testing, and tests of rollover resistance. Assessments are done with various methods and tools, including Computer crash simulation (typically finite element analysis), crash test dummy, and partial system sled and full vehicle crashes.</p>
	
	<p><b>Fuel economy/emissions:</b> Fuel economy is the measured fuel efficiency of the vehicle in miles per gallon or kilometers per liter. Emissions testing includes the measurement of vehicle emissions, including hydrocarbons, nitrogen oxides (NOx), carbon monoxide (CO), carbon dioxide (CO2), and evaporative emissions.</p>
	
	<p><b>NVH engineering (noise, vibration, and harshness):</b> NVH is the customer's feedback (both tactile [felt] and audible [heard]) from the vehicle. While sound can be interpreted as a rattle, squeal, or hot, a tactile response can be seat vibration or a buzz in the steering wheel. This feedback is generated by components either rubbing, vibrating, or rotating. NVH response can be classified in various ways: powertrain NVH, road noise, wind noise, component noise, and squeak and rattle. Note, there are both good and bad NVH qualities. The NVH engineer works to either eliminate bad NVH or change the “bad NVH” to good (i.e., exhaust tones).</p>
	
	<p><b>Vehicle Electronics:</b> Automotive electronics is an increasingly important aspect of automotive engineering. Modern vehicles employ dozens of electronic systems. These systems are responsible for operational controls such as the throttle, brake and steering controls; as well as many comfort and convenience systems such as the HVAC, infotainment, and lighting systems. It would not be possible for automobiles to meet modern safety and fuel economy requirements without electronic controls.</p>
	
	<p><b>Performance:</b> Performance is a measurable and testable value of a vehicle's ability to perform in various conditions. Performance can be considered in a wide variety of tasks, but it's generally associated with how quickly a car can accelerate (e.g. standing start 1/4 mile elapsed time, 0–60 mph, etc.), its top speed, how short and quickly a car can come to a complete stop from a set speed (e.g. 70-0 mph), how much g-force a car can generate without losing grip, recorded lap times, cornering speed, brake fade, etc. Performance can also reflect the amount of control in inclement weather (snow, ice, rain).</p>
	
	<p><b>Shift quality:</b> Shift quality is the driver's perception of the vehicle to an automatic transmission shift event. This is influenced by the powertrain (engine, transmission), and the vehicle (driveline, suspension, engine and powertrain mounts, etc.) Shift feel is both a tactile (felt) and audible (heard) response of the vehicle. Shift quality is experienced as various events: Transmission shifts are felt as an upshift at acceleration (1–2), or a downshift maneuver in passing (4–2). Shift engagements of the vehicle are also evaluated, as in Park to Reverse, etc.</p>
	
	<p><b>Durability / corrosion engineering:</b> Durability and corrosion engineering is the evaluation testing of a vehicle for its useful life. Tests include mileage accumulation, severe driving conditions, and corrosive salt baths.</p>
	
	<p><b>Drivability:</b> Drivability is the vehicle's response to general driving conditions. Cold starts and stalls, RPM dips, idle response, launch hesitations and stumbles, and performance levels.</p>
	
	<p><b>Cost:</b> The cost of a vehicle program is typically split into the effect on the variable cost of the vehicle, and the up-front tooling and fixed costs associated with developing the vehicle. There are also costs associated with warranty reductions and marketing.</p>
	
	<p><b>Program timing:</b> To some extent programs are timed with respect to the market, and also to the production schedules of the assembly plants. Any new part in the design must support the development and manufacturing schedule of the model.</p>
	
	<p><b>Assembly feasibility:</b> It is easy to design a module that is hard to assemble, either resulting in damaged units or poor tolerances. The skilled product development engineer works with the assembly/manufacturing engineers so that the resulting design is easy and cheap to make and assemble, as well as delivering appropriate functionality and appearance.</p>
	
	<p><b>Quality management:</b> Quality control is an important factor within the production process, as high quality is needed to meet customer requirements and to avoid expensive recall campaigns. The complexity of components involved in the production process requires a combination of different tools and techniques for quality control. Therefore, the International Automotive Task Force (IATF), a group of the world's leading manufacturers and trade organizations, developed the standard ISO/TS 16949. This standard defines the design, development, production, and when relevant, installation and service requirements. Furthermore, it combines the principles of ISO 9001 with aspects of various regional and national automotive standards such as AVSQ (Italy), EAQF (France), VDA6 (Germany) and QS-9000 (USA). In order to further minimize risks related to product failures and liability claims of automotive electric and electronic systems, the quality discipline functional safety according to ISO/IEC 17025 is applied.</p>
		
	<p>Since the 1950s, the comprehensive business approach total quality management, TQM, helps to continuously improve the production process of automotive products and components. Some of the companies who have implemented TQM include Ford Motor Company, Motorola and Toyota Motor Company.</p>
	
<br>
<br>

<?php
	require 'autoengslideshow.php'
?>

</div>
	
<br>
<br>
<br>
<br>
<br>

</body>
</html>